version: '3'

volumes:
  pg_data:
  static_volume:
  media:

services:
  db:
    container_name: pgsql-foodgram.local
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: django-foodgram.local
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media:/app/media/

  frontend:
    container_name: front-foodgram.local
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    depends_on:
      - backend


  gateway:
    container_name: foodgram-proxy.local
    build: ./nginx/
    env_file: .env
    ports:
      - ${EXTERNAL_PORT}:80
    volumes:
      - static_volume:/staticfiles
      - media:/app/media
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend